"""
Leaf.py
This file contains the class Leaf
Leaf is used to define the leaf attacks generated by Twisted Lumber
When no child class is used leaves fall slowly to the bottom of the screen
"""

import pygame
from pygame.sprite import Sprite

class Leaf(Sprite):
    def __init__(self, w_settings, x, y, facing_left, cur_time=None, start_angle=None):
        super(Leaf, self).__init__()
        self.w_settings = w_settings
        self.x = x
        self.y = y
        self.facing_left = facing_left

        self.rect = pygame.Rect(self.x, self.y, self.w_settings.TL_leaf_width, self.w_settings.TL_leaf_height)
        if facing_left:
            self.image = self.w_settings.TL_leaf_left_image
        else:
            self.image = self.w_settings.TL_leaf_right_image

        # Variables to check if the leaf needs to be deleted
        self.off_bottom = False
        self.off_top = False
        self.off_left = False
        self.off_right = False

    def update_pos(self, cur_time):
        self.rect.x = int(self.x)
        self.rect.y = int(self.y)

        if self.rect.top > self.w_settings.screen_height:
            self.off_bottom = True

    def ready_to_delete(self):
        if self.off_bottom:
            return True
        return False
