"""
LeafSpiral.py
This file contains the class LeafSpiral
LeafSpiral is used to define a leaf spiral attack generated by Twisted Lumber
Leaf Spiral has a leaf spiral around in a circle while slowly increasing velocity away from the center
"""

import math
from Classes.Leaf import Leaf


class LeafSpiral(Leaf):
    def __init__(self, w_settings, x, y, facing_left, cur_time=None, start_angle=None):
        super(LeafSpiral, self).__init__(w_settings, x, y, facing_left, cur_time, start_angle)

        self.center_x = self.rect.centerx
        self.center_y = self.rect.centery
        self.radius = 0
        self.radius_vel = 0
        self.angle = start_angle

    def update_pos(self, cur_time, time_passed):
        # Determine the new radius
        if self.init_delay.is_active(cur_time):
            self.radius_vel += self.w_settings.TL_leaf_spiral_init_radius_accel * time_passed
        else:
            self.radius_vel += self.w_settings.TL_leaf_spiral_radius_accel * time_passed

        self.radius += self.radius_vel

        # Determine the new angle
        if self.facing_left:
            self.angle -= self.w_settings.TL_leaf_spiral_angle_vel * time_passed
        else:
            self.angle += self.w_settings.TL_leaf_spiral_angle_vel* time_passed

        # Apply all changes
        self.rect.centerx = int(self.center_x + math.cos(self.angle) * self.radius)
        self.rect.centery = int(self.center_y + math.sin(self.angle) * self.radius)

        # For the ready to delete function
        if self.rect.right < 0:
            self.off_left = True
        if self.rect.left > self.w_settings.screen_width:
            self.off_right = True
        if self.rect.top > self.w_settings.screen_height:
            self.off_bottom = True
        if self.rect.bottom < 0:
            self.off_top = True

    def ready_to_delete(self):
        # Check if the leaf has spiraled far enough to where it won't appear on the screen anymore
        if self.off_left and self.off_right and self.off_bottom and self.off_top:
            return True
        return False
