"""
LeafDart.py
This file contains the class LeafDart
LeafDart is used to define a leaf dart attack generated by Twisted Lumber
Leaf Dart starts as a leaf frozen in place, which then moves quickly to the left or right
"""

from Classes.Leaf import Leaf
from Classes.Delay import Delay


class LeafDart(Leaf):
    def __init__(self, w_settings, x, y, facing_left, cur_time, start_angle=None):
        super(LeafDart, self).__init__(w_settings, x, y, facing_left, cur_time, start_angle)

        self.dart_delay = Delay(self.w_settings.TL_leaf_dart_wait_period)
        self.dart_delay.begin(cur_time)

    def update_pos(self, cur_time):
        if not self.dart_delay.is_active(cur_time):
            if self.facing_left:
                self.x += self.w_settings.TL_leaf_dart_speed * -1
            else:
                self.x += self.w_settings.TL_leaf_dart_speed
        self.rect.x = int(self.x)
        self.rect.y = int(self.y)

        if self.rect.right < 0 or self.rect.left > self.w_settings.screen_width:
            self.off_left = True
            self.off_right = True

    def ready_to_delete(self):
        if self.off_left or self.off_right:
            return True
        return False
